### PR TITLE
reduce text and horizontal legend

### PR DESCRIPTION
**Pull request by cnell-usgs**
This was really neat to dig into, I'm suggesting a few minor changes:
- I moved some of your data files to s3 to be pulled in directly from there and avoid committing large files
- In `a_tale_of_two_basins.R` I added a step to download site info directly from NWIS via `dataRetrieval` so the script doesn't need depend on the external csv
- Made a few text features (title, legend title) bold to match the axis labelling
- flipped the legend to be horizontal and adjusting spacing slightly
- reduced the amount of test, trying to be concise and keep the focus on the plot. 
- Modified the title of the first chart to "When are U.S. Rivers Wet or Dry?"
- - added a point for the off-the-chart wettest day

I was not able to recreate the map because I could not find the `gagesII_metadata.csv` 

Here's the final images:
Wettest_Day_of_the_Year
Wettest_Day_of_the_Year_CRB

### CODE REVIEW

**Comment by csimeone-usgs** [comment]
Overall I think that the updated figures look great. Thanks for making those changes.

One question I have about the code is the change of the paths from referencing files in 11_circular_csimeone/data_in to just data_in, won't that make it so that the scripts can't be run from their current location in overall directory?

What are your thoughts on moving the 3rd line of the 2nd figure 'to each gage' up to the second line if it will fit so that both lines are of similar length?

I'm fine with removing the "Note that this measurement omits water in ungaged rivers and in some cases counts river with multiple gages more than once" from the figure itself, but think that its important on include this in the text blurb attached to the post.

Do you want me to send you the files for plotting the map? I link to where they are downloaded from in the Readme as well as in the code I think.

**Comment by cnell-usgs** [comment]
Moved the text Up. Will add that map text into the tweet itself. I was working in a project based out of the subdirectory and made that filepath edit to be consistent across the whole repo

**Comment by cnell-usgs** [comment]
Updated chart: Wettest_Day_of_the_Year_CRB

**Comment by csimeone-usgs** [comment]
Awesome, looks great.

**Pull request merged**
