### PR TITLE
Draft submission for topic 27: uncertainties future

### PR DESCRIPTION
**Pull request by jdiaz4302**
90% of the work/code occurs in `notebooks/figure_creation.ipynb`

`notebooks/minimal_story.ipynb` is my attempt at the story/narrative (so I would say **this is my main submission**). It is the context for understanding the bigger, fancier gif.

The `.gif` didn't commit because of the ignore settings, but I'm attaching it below for reference.

forecast_comparison

I'll double check that I can put the data here tomorrow and upload the remaining <10% code that's concerned with minimally preparing the raw data for these notebooks

Thanks for the help to this point 👏🏼

### CODE REVIEW

**Comment by jdiaz4302** [comment]
Just realized I messed up the plot's title code when I was trying to tidy it up. Fixed now and here's the gif with a properly changing date in the title

forecast_comparison

**Review by hcorson-dosch-usgs — COMMENTED** [review]
### **Overall Comments**

I really love the story you've crafted, and you've used some clever techniques to pull out and highlight the data. I love the use of `fill_between()` and the `y1` and `y2` distributions to highlight the impact of DA on the distribution of predictions. Your `minimal_story` notebook does an excellent job of presenting the data and the story you're telling.

---------------------------------
### **Design Comments**

* I love the dark theme and the colors you chose, as well as the use of white to highlight the actual observation.
* I think somewhere it needs to be made clear that these are forecasted stream temperature predictions -- maybe the title could be enlarged and changed to 'How does data assimilation affect stream temperature forecasts'?
* I love how you've laid out the color bars horizontally, but think we could condense the bars and the labels so that they aren't quite as spread out
  * Maybe something like this? If it's too tedious to code, we could leave as is in the ipynb and I could modify the gif frames in adobe illustrator/photoshop 
image
* I also think the day 7 color might be a bit too dim. Maybe worth testing to see how it looks if you slightly reduce the amount by which the alpha decreases based on lead time?
* Consider using 'forecasts' in place of 'model' in the legend, since the word model isn't used elsewhere in the gif
* I might add 'temperature' to the x-axis label - maybe 'difference from observed temperature' 

Overall, I think the trickiest bit is whether the viewer can grasp what is being shown by the purple and orange distributions without reading your helpful story walkthrough. We can put some of that walkthrough in sub-tweets, but the viewer will first be presented with the main gif.
  * I think there's a range of ways we could add a bit more context to this gif, with some options being more involved than others. I think one lower investment option would be for us to leave the code and generated gif as is, but then use the gif frames to build a custom gif in Adobe Photoshop, where it would be possible for me to slow down certain frames and add annotations. But I'd be curious to get your thoughts as to whether or not annotations would be helpful, and what annotations you might add.
  * A higher investment option would be to add in a couple of introductory frames that allow for annotations and provide the walkthrough you give in 'minimal_story.ipynb'. I know you have your sprint coming up, so if you feel like that would be a good direction, that's something I could take on adding in. Adding more length/content to a gif isn't always the right choice (I've done it in the past and seen it not pay off), but we could discuss and see if it would make sense here.
  * I've also been toying with the idea of whether it would make sense to plot the gif frames by lead time rather than by issue date (note - this may be too big of a lift or may not make sense). My thinking was that it might make it feel like there is less for the viewer to track between two frames, and help focus on the impact of DA as lead time decreases. If you send your data file I'd be happy to try it out.

If you have a few minutes, maybe we could chat today?

------------------------------
### **Code Comments**

I just had a few _suggested_ edits that would add a bit more context through additional comments and headers.

**minimal_story.ipynb**
* I love this walkthrough -- what a good idea to put it together. I wonder if we could use images 2, 3, 4, and 5 as sub-tweets to the main tweet, along with your accompanying description?
* I'd spell out data assimilation rather than using the acronym DA

**figure_creation.ipynb**
* I'd separate out your package imports from your variable definitions into two separate cells
  * If defining some colors with variables, I'd define them all
* Might be good to add a comment that quick defines `issue_time` as the date the forecast is issued, and `time` as the date for which the forecast is made
* In cell 6 - maybe state in your comments that you're subtracting the actual observed temp (pulled as `prev_day_DA['obs_max_temp_c'].unique()`) from the x distribution in order to display how predicted temperatures differ from the observed temperature
* Write out data assimilation in place of the acronym DA
* Might be helpful to add a markdown heading for each plot stating your intent. E.g. 'plot distribution of predicted temperatures and observed temperature' for the first plot
  * Some of the text beneath figures provides the takeaway for the figure (which is super helpful), and then pivots and introduces the concept for the next figure -- maybe you could consider splitting this text into two cells, with a markdown heading in between?
* In the text below the figure generated in cell 7, where you say "but now we have assigned a higher probability to the values closer to where the observation ended up occurring at" -- could that accurately be rephrased to "but now there is a higher probability that the predicted values will fall closer to the actual observed temperature"? If so I think that might be more clear for the reader
* In cell 13 where you are extracting the minimum and maximum differences between predicted and observed values 'across the days of interest' I'd add a note that those days of interests are issue dates on which forecasts are made for the 7 forecast dates of interest (and that's why you're iterating over a range of -7 to 7)
* In cell 14 I'd name the color maps to reflect whether they pertain to DA or no-DA predictions

**Comment by hcorson-dosch-usgs** [comment]
Also - when you get the chance, could add a comment here providing the following:

1. Overall messaging. How does the chart connect to the day/category? What is the 1-2 sentence takeaway?
2. The data source and variables used. Where can the data be found? Is it from USGS or elsewhere? Did you do any pre-processing?
3. Tools & libraries used

If the raw data you reference preparing is available on ScienceBase, that would be great to note. Or if if can't be shared, let's just discuss how to make note of that in the repo.

It would also be great if you could add a `README.md` that briefly describes what your code builds, describes the different notebooks included in your subdirectory, and includes the final gif, similar to what is provided [here](https://github.com/USGS-VIZLAB/chart-challenge-22/tree/main/03_historical_jread) and [here](https://github.com/USGS-VIZLAB/chart-challenge-22/tree/main/04_flora_cnell)

**Comment by jdiaz4302** [comment]
Gif with label changes - the legend was too time consuming to adjust via the code

forecast_comparison

Gif with label changes by forecast lead time. I like the flow of the original approach better, the last frame feels more crash-y (I like seeing the distributions fall into a good, last place one a time rather than all at once), but I do see the arguments for this one:

forecast_comparison

Gif with some extra context at the beginning. Didn't have much time to polish the presentation of the extra context -

forecast_comparison

**Comment by hcorson-dosch-usgs** [comment]
Thanks for exploring these changes, Jeremy! Let's stick with the animation by issue date, since you feel that better highlights the data. I like the additional context that you've added in the final gif you shared, though it does move by quickly. If you'd like to move ahead with that version, I think it would make sense for me to bring the frames that you've generated into Photoshop, where I could slow the intro frames down, condense the legend,  and add some annotations, based on the storyline you present in `'minimal_story.ipynb'`. What do you think?

**Comment by jdiaz4302** [comment]
I agree, that would be great and thank you for doing that!

**Comment by hcorson-dosch-usgs** [comment]
Gif:
Jeremy_gif

**Review by hcorson-dosch-usgs — APPROVED** [review]
Everything looks great -- thanks, Jeremy!

**Pull request merged**
